--save /etc/pacman.d/mirrorlist
--protocol https
--country US,CA
--age 12
--include '(losangeles[.]mirror[.]pkgbuild[.]com|mirrors[.]rit[.]edu|mirrors[.]ocf[.]berkeley[.]edu|mirror[.]csclub[.]uwaterloo[.]ca|mirrors[.]lug[.]mtu[.]edu)'
--sort score
--number 5
